/**
 * Permission Types for Admin RBAC
 * This enum matches the PermissionType enum in Prisma schema
 */
export enum PermissionType {
  // Users Management
  USERS_VIEW = 'USERS_VIEW',
  USERS_CREATE = 'USERS_CREATE',
  USERS_UPDATE = 'USERS_UPDATE',
  USERS_DELETE = 'USERS_DELETE',
  USERS_ACTIVATE = 'USERS_ACTIVATE',
  USERS_DEACTIVATE = 'USERS_DEACTIVATE',

  // Salons Management
  SALONS_VIEW = 'SALONS_VIEW',
  SALONS_CREATE = 'SALONS_CREATE',
  SALONS_UPDATE = 'SALONS_UPDATE',
  SALONS_DELETE = 'SALONS_DELETE',
  SALONS_APPROVE = 'SALONS_APPROVE',
  SALONS_SUSPEND = 'SALONS_SUSPEND',
  SALONS_ACTIVATE = 'SALONS_ACTIVATE',

  // Packages Management
  PACKAGES_VIEW = 'PACKAGES_VIEW',
  PACKAGES_CREATE = 'PACKAGES_CREATE',
  PACKAGES_UPDATE = 'PACKAGES_UPDATE',
  PACKAGES_DELETE = 'PACKAGES_DELETE',

  // Subscriptions Management
  SUBSCRIPTIONS_VIEW = 'SUBSCRIPTIONS_VIEW',
  SUBSCRIPTIONS_UPDATE = 'SUBSCRIPTIONS_UPDATE',
  SUBSCRIPTIONS_DELETE = 'SUBSCRIPTIONS_DELETE',

  // Reviews Management
  REVIEWS_VIEW = 'REVIEWS_VIEW',
  REVIEWS_DELETE = 'REVIEWS_DELETE',
  REVIEWS_MODERATE = 'REVIEWS_MODERATE',

  // Reports Management
  REPORTS_VIEW = 'REPORTS_VIEW',
  REPORTS_RESOLVE = 'REPORTS_RESOLVE',
  REPORTS_DELETE = 'REPORTS_DELETE',

  // Payments Management
  PAYMENTS_VIEW = 'PAYMENTS_VIEW',
  PAYMENTS_REFUND = 'PAYMENTS_REFUND',

  // Notifications Management
  NOTIFICATIONS_VIEW = 'NOTIFICATIONS_VIEW',
  NOTIFICATIONS_SEND = 'NOTIFICATIONS_SEND',
  NOTIFICATIONS_BROADCAST = 'NOTIFICATIONS_BROADCAST',

  // Content Management
  CONTENT_VIEW = 'CONTENT_VIEW',
  CONTENT_MODERATE = 'CONTENT_MODERATE',
  CONTENT_DELETE = 'CONTENT_DELETE',

  // Admin Management
  ADMINS_VIEW = 'ADMINS_VIEW',
  ADMINS_CREATE = 'ADMINS_CREATE',
  ADMINS_UPDATE = 'ADMINS_UPDATE',
  ADMINS_DELETE = 'ADMINS_DELETE',
  ADMINS_PERMISSIONS_MANAGE = 'ADMINS_PERMISSIONS_MANAGE',

  // Dashboard & Analytics
  DASHBOARD_VIEW = 'DASHBOARD_VIEW',
  ANALYTICS_VIEW = 'ANALYTICS_VIEW',
  REPORTS_EXPORT = 'REPORTS_EXPORT',

  // Settings
  SETTINGS_VIEW = 'SETTINGS_VIEW',
  SETTINGS_UPDATE = 'SETTINGS_UPDATE',
  SYSTEM_SETTINGS_MANAGE = 'SYSTEM_SETTINGS_MANAGE',

  // Billing
  BILLING_VIEW = 'BILLING_VIEW',
  INVOICES_VIEW = 'INVOICES_VIEW',
  INVOICES_CREATE = 'INVOICES_CREATE',
  INVOICES_UPDATE = 'INVOICES_UPDATE',
}

